# Generated by Django 3.1.7 on 2021-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deparments',
            fields=[
                ('DeparmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DeparmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Deparment', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFildName', models.CharField(max_length=100)),
            ],
        ),
    ]
